name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: 
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - name: Restore dependencies
        run: dotnet restore Backend.Tests/Backend.Tests.csproj

      - name: Build
        run: dotnet build Backend.Tests/Backend.Tests.csproj --no-restore

      - name: Run unit tests
        run: dotnet test Backend.Tests/Backend.Tests.csproj --no-build --verbosity normal
      
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache-dependency-path: package-lock.json
          cache: "npm"

      - name: Restore npm dependencies
        run: npm ci

      - name: Build frontend with Vite
        run: npm run build
      
      - name: Run dotnet server
        run: |
          npm run backend &
          npx wait-on http://localhost:5001
          echo "Server started"

      - name: Run api tests
        run: npm run test:api


  # playwright-tests:
  #   needs: unit-tests
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-node@v4
  #     with:
  #       node-version: lts/*
  #   - name: Install dependencies
  #     run: npm ci
  #   - name: Install Playwright Browsers
  #     run: npx playwright install --with-deps
  #   - name: Run Playwright tests
  #     run: npx playwright test
  #   - uses: actions/upload-artifact@v4
  #     if: ${{ !cancelled() }}
  #     with:
  #       name: playwright-report
  #       path: playwright-report/
  #       retention-days: 30
